services:
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  backend:
    build: ./services
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
      - "5001:5001"
  
    
  